/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'
import { GLTFResult } from '../../types/Room';

export function Room() {
  const { nodes, materials } = useGLTF('/room.glb') as unknown as GLTFResult
  return (
    <group dispose={null} scale={0.6} rotation={[0, Math.PI / 2 + 3.9, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[-2.425, 0, 0]}
        scale={[0.416, 0.416, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Masa.geometry}
        material={materials.Brown4}
        position={[-1.757, -0.804, 0.084]}
      />
      <group position={[-1.766, -1.472, 1.822]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials.Brown4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_2.geometry}
          material={materials.Brown5}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dolap_sag2.geometry}
        material={materials.Brown4}
        position={[-1.819, -1.544, -1.811]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dolap_ustu.geometry}
        material={materials.Brown4}
        position={[0.592, -0.804, -1.684]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.084, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Raf_sag.geometry}
        material={materials.Brown}
        position={[-0.245, 1.421, -1.738]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <group
        position={[2.406, -1.472, -1.771]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1, 0.863, 0.992]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials.Brown4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_2.geometry}
          material={materials.Brown5}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor.geometry}
        material={materials.Brown6}
        position={[2.213, -2.078, 1.815]}
        scale={[1.019, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Kupa.geometry}
        material={materials.White}
        position={[-1.643, -0.619, -0.927]}
        rotation={[0, 0.653, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Saksı.geometry}
        material={materials.Brown5}
        position={[1.107, 1.749, -1.756]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pencere.geometry}
        material={materials['Brown.2']}
      />
      <group position={[0.328, 0.381, -2.227]} scale={[1.225, 0.615, 0.067]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_1.geometry}
          material={materials['Brown.2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_2.geometry}
          material={materials.Green}
        />
      </group>
      <group position={[-1.848, -0.718, 1.725]} scale={0.262}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_1.geometry}
          material={materials.Brown5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_2.geometry}
          material={materials.Cream3}
        />
      </group>
      <group position={[-1.848, -0.645, 1.522]} rotation={[-0.213, 0.039, -0.105]} scale={0.262}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_1.geometry}
          material={materials.Orange}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_2.geometry}
          material={materials.Cream3}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[2.11, -0.546, -1.254]}
        rotation={[0, 0.496, 0]}
        scale={[0.138, 0.067, 0.067]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Raf_sag001.geometry}
        material={materials.Brown}
        position={[-1.811, 0.885, 0.171]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.854, 1, 0.683]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sapka002.geometry}
        material={materials.Cream4}
        position={[-1.841, -0.281, 0.305]}
        scale={0.274}
      />
      <group position={[-1.848, -0.691, 1.128]} rotation={[-0.105, 0, 0]} scale={0.262}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006.geometry}
          material={materials.Blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_1.geometry}
          material={materials.Cream3}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sapka004.geometry}
        material={materials.Cream4}
        position={[-1.925, 1.162, -0.213]}
        rotation={[-0.262, 0, 0]}
        scale={0.262}
      />
      <group position={[-1.739, 1.24, -0.213]} rotation={[-0.234, 0.072, -0.291]} scale={0.262}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008.geometry}
          material={materials.Brown5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008_1.geometry}
          material={materials.Cream}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sapka006.geometry}
        material={materials.Brown5}
        position={[-0.55, -0.499, -1.739]}
        rotation={[0, 0.086, 0.782]}
        scale={0.274}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sapka007.geometry}
        material={materials.Brown5}
        position={[-0.728, -0.291, -1.724]}
        rotation={[0, 0.086, -0.247]}
        scale={0.274}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sapka008.geometry}
        material={materials.Cream4}
        position={[-0.366, -0.37, -1.404]}
        rotation={[-0.597, 0.443, 0.254]}
        scale={0.244}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials['Dark green']}
        position={[1.122, 1.964, -1.67]}
        rotation={[-2.007, 1.401, 1.348]}
        scale={[0.35, 0.35, 0.077]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials['Dark green']}
        position={[1.069, 1.963, -1.712]}
        rotation={[-0.245, 0.69, -0.703]}
        scale={[0.207, 0.207, 0.046]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials['Dark green']}
        position={[1.022, 1.961, -1.761]}
        rotation={[-0.171, -0.45, -0.74]}
        scale={[0.359, 0.359, 0.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials['Dark green']}
        position={[1.096, 1.963, -1.811]}
        rotation={[-0.828, -1.314, -1.672]}
        scale={[0.256, 0.256, 0.057]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials['Dark green']}
        position={[1.174, 1.959, -1.809]}
        rotation={[-2.953, -0.616, 2.586]}
        scale={[0.396, 0.396, 0.088]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials['Dark green']}
        position={[1.214, 1.961, -1.741]}
        rotation={[-3.118, 0.39, 2.57]}
        scale={[0.209, 0.209, 0.046]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials['Dark green']}
        position={[1.159, 1.939, -1.713]}
        rotation={[-2.983, 1.045, 2.764]}
        scale={[0.31, 0.31, 0.069]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials['Dark green']}
        position={[1.087, 1.918, -1.698]}
        rotation={[-0.468, 1.142, -0.061]}
        scale={[0.244, 0.244, 0.054]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials['Dark green']}
        position={[1.048, 1.932, -1.734]}
        rotation={[-0.154, 0.023, -0.247]}
        scale={[0.357, 0.357, 0.079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials['Dark green']}
        position={[1.073, 1.936, -1.795]}
        rotation={[-0.303, -0.893, -0.509]}
        scale={[0.252, 0.252, 0.056]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials['Dark green']}
        position={[1.143, 1.932, -1.829]}
        rotation={[-2.81, -1.081, 3.111]}
        scale={[0.297, 0.297, 0.066]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials['Dark green']}
        position={[1.185, 1.936, -1.778]}
        rotation={[-2.951, -0.162, 2.826]}
        scale={[0.266, 0.266, 0.059]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials['Dark green']}
        position={[1.123, 1.959, -1.776]}
        rotation={[-2.827, -1.053, 2.752]}
        scale={[0.257, 0.257, 0.057]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials['Dark green']}
        position={[1.066, 1.963, -1.754]}
        rotation={[-0.308, -0.905, -1.107]}
        scale={[0.18, 0.18, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={materials['Dark green']}
        position={[1.098, 1.959, -1.729]}
        rotation={[-0.422, 1.079, -0.371]}
        scale={[0.257, 0.257, 0.057]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={materials['Dark green']}
        position={[1.155, 1.963, -1.748]}
        rotation={[-2.896, 0.689, 2.06]}
        scale={[0.18, 0.18, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={materials['Dark green']}
        position={[1.048, 1.932, -1.734]}
        rotation={[0.026, 0.543, -0.021]}
        scale={[0.357, 0.357, 0.079]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane019.geometry}
        material={materials['Dark green']}
        position={[1.143, 1.932, -1.681]}
        rotation={[3.091, 1.113, -3.104]}
        scale={[0.301, 0.301, 0.067]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={materials['Dark green']}
        position={[1.196, 1.932, -1.77]}
        rotation={[3.116, -0.468, 3.122]}
        scale={[0.319, 0.319, 0.071]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane021.geometry}
        material={materials['Dark green']}
        position={[1.246, 1.917, -1.766]}
        rotation={[-2.951, 0.694, 2.702]}
        scale={[0.18, 0.18, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane022.geometry}
        material={materials['Dark green']}
        position={[1.071, 1.929, -1.668]}
        rotation={[-0.457, 1.313, 0.277]}
        scale={[0.243, 0.243, 0.054]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane042.geometry}
        material={materials.winddow_emission}
        position={[-2.247, 0.006, 0.001]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.522, 0.522, 1.047]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.White}
        position={[-2.126, 1.858, -1.732]}
        rotation={[0, 0, 0.074]}
        scale={[0.064, 0.346, 0.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.Black}
        position={[-2.126, 1.858, -1.732]}
        rotation={[0, 0, 0.074]}
        scale={[0.059, 0.323, 0.213]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.White}
        position={[-1.973, 1.858, -1.732]}
        rotation={[0, 0, 0.049]}
        scale={[0.064, 0.346, 0.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.Blue}
        position={[-1.973, 1.858, -1.732]}
        rotation={[0, 0, 0.049]}
        scale={[0.059, 0.323, 0.213]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.White}
        position={[-1.822, 1.858, -1.732]}
        rotation={[0, 0, 0.039]}
        scale={[0.064, 0.346, 0.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.Brown4}
        position={[-1.822, 1.858, -1.732]}
        rotation={[0, 0, 0.039]}
        scale={[0.059, 0.323, 0.213]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.White}
        position={[-1.672, 1.858, -1.732]}
        rotation={[0, 0, 0.021]}
        scale={[0.064, 0.346, 0.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials.Green}
        position={[-1.672, 1.858, -1.732]}
        rotation={[0, 0, 0.021]}
        scale={[0.059, 0.323, 0.213]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials.White}
        position={[-1.519, 1.858, -1.732]}
        scale={[0.064, 0.346, 0.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials.Cream3}
        position={[-1.519, 1.858, -1.732]}
        scale={[0.059, 0.323, 0.213]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials.White}
        position={[-1.06, 1.572, -1.731]}
        rotation={[0, 0.851, 1.554]}
        scale={[0.064, 0.346, 0.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials.Black}
        position={[-1.06, 1.572, -1.731]}
        rotation={[0, 0.851, 1.554]}
        scale={[0.059, 0.323, 0.213]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials.White}
        position={[-1.113, 1.719, -1.734]}
        rotation={[0, 1.265, 1.554]}
        scale={[0.064, 0.346, 0.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials.Orange}
        position={[-1.113, 1.719, -1.734]}
        rotation={[0, 1.265, 1.554]}
        scale={[0.059, 0.323, 0.213]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials.White}
        position={[-1.195, 1.863, -1.734]}
        rotation={[0, 1.519, 1.554]}
        scale={[0.064, 0.346, 0.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials.Blue}
        position={[-1.195, 1.863, -1.734]}
        rotation={[0, 1.519, 1.554]}
        scale={[0.059, 0.323, 0.213]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials.White}
        position={[1.855, -0.532, -1.721]}
        rotation={[Math.PI, 1.091, -1.288]}
        scale={[0.064, 0.346, 0.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={materials.Green}
        position={[1.855, -0.532, -1.721]}
        rotation={[Math.PI, 1.091, -1.288]}
        scale={[0.059, 0.323, 0.213]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials.White}
        position={[1.884, -0.419, -1.607]}
        rotation={[-Math.PI, 0.958, -1.288]}
        scale={[0.064, 0.346, 0.228]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials.Blue}
        position={[1.884, -0.419, -1.607]}
        rotation={[Math.PI, 0.958, -1.288]}
        scale={[0.059, 0.323, 0.213]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.Brown4}
        position={[-0.003, -1.169, 0]}
        scale={[0.314, 0.064, 0.314]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials.Brown}
        position={[0.219, -1.831, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.019, 0.153, 0.026]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials.Brown}
        position={[0.064, -0.947, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.034, 0.125, 0.044]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Dark Yellow']}
        position={[-0.292, 0.701, -2.179]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials['Dark Yellow']}
        position={[-0.234, 0.661, -2.179]}
        rotation={[Math.PI / 2, -1.17, 0]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane023.geometry}
        material={materials['Dark Yellow']}
        position={[-0.26, 0.601, -2.179]}
        rotation={[-Math.PI / 2, -0.677, -Math.PI]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={materials['Dark Yellow']}
        position={[-0.326, 0.598, -2.179]}
        rotation={[-Math.PI / 2, 0.597, -Math.PI]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={materials['Dark Yellow']}
        position={[-0.345, 0.663, -2.179]}
        rotation={[Math.PI / 2, 1.316, 0]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials.Yellow}
        position={[-0.292, 0.643, -2.178]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.069}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={materials.Orange}
        position={[1.08, 0.536, -2.179]}
        rotation={[Math.PI / 2, 0.319, 0]}
        scale={0.044}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials.Orange}
        position={[1.13, 0.518, -2.179]}
        rotation={[Math.PI / 2, -0.909, 0]}
        scale={0.044}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane028.geometry}
        material={materials.Orange}
        position={[1.132, 0.467, -2.179]}
        rotation={[-Math.PI / 2, -0.899, Math.PI]}
        scale={0.044}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane029.geometry}
        material={materials.Orange}
        position={[1.079, 0.447, -2.179]}
        rotation={[-Math.PI / 2, 0.308, -Math.PI]}
        scale={0.044}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={materials.Orange}
        position={[1.049, 0.491, -2.179]}
        rotation={[Math.PI / 2, 1.514, 0]}
        scale={0.044}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials.Yellow}
        position={[1.094, 0.492, -2.178]}
        rotation={[Math.PI / 2, 0.373, 0]}
        scale={0.057}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane031.geometry}
        material={materials['Dark Yellow']}
        position={[0.348, 0.302, -2.179]}
        rotation={[Math.PI / 2, 0.6, 0]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane032.geometry}
        material={materials['Dark Yellow']}
        position={[0.397, 0.302, -2.179]}
        rotation={[Math.PI / 2, -0.577, 0]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane033.geometry}
        material={materials['Dark Yellow']}
        position={[0.408, 0.257, -2.179]}
        rotation={[-Math.PI / 2, -1.246, Math.PI]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane034.geometry}
        material={materials['Dark Yellow']}
        position={[0.367, 0.232, -2.179]}
        rotation={[-Math.PI / 2, 0.046, -Math.PI]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane035.geometry}
        material={materials['Dark Yellow']}
        position={[0.331, 0.258, -2.179]}
        rotation={[-Math.PI / 2, 1.401, Math.PI]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials.Yellow}
        position={[0.371, 0.27, -2.178]}
        rotation={[Math.PI / 2, 0.6, 0]}
        scale={0.048}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane036.geometry}
        material={materials.Blue}
        position={[0.332, 0.283, -2.177]}
        rotation={[Math.PI / 2, 1.231, 0]}
        scale={0.037}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane037.geometry}
        material={materials.Blue}
        position={[0.373, 0.313, -2.177]}
        rotation={[Math.PI / 2, 0.055, 0]}
        scale={0.037}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane038.geometry}
        material={materials.Blue}
        position={[0.41, 0.282, -2.177]}
        rotation={[Math.PI / 2, -1.264, 0]}
        scale={0.037}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane039.geometry}
        material={materials.Blue}
        position={[0.391, 0.236, -2.177]}
        rotation={[-Math.PI / 2, -0.586, -Math.PI]}
        scale={0.037}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane040.geometry}
        material={materials.Blue}
        position={[0.345, 0.237, -2.177]}
        rotation={[-Math.PI / 2, 0.769, -Math.PI]}
        scale={0.037}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve.geometry}
        material={materials['Dark green']}
        position={[-0.307, 0.337, -2.197]}
        rotation={[0, 0, 1.558]}
        scale={0.135}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve001.geometry}
        material={materials['Dark green']}
        position={[1.107, 0.191, -2.197]}
        rotation={[0, 0, 1.558]}
        scale={0.135}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve002.geometry}
        material={materials['Dark green']}
        position={[0.374, 0.125, -2.171]}
        rotation={[-Math.PI, 0, 1.558]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials.Brown5}
        position={[-1.516, -0.64, -1.53]}
        scale={0.085}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials.Glass}
        position={[-1.516, -0.6, -1.53]}
        scale={[0.089, 0.107, 0.089]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane041.geometry}
        material={materials['Brown.2']}
        position={[-2.322, 2.471, -2.321]}
        scale={0.142}
      />
      <group position={[-1.813, 0.307, -2.172]} scale={[0.209, 0.286, 0.041]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube039.geometry}
          material={materials.Brown5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube039_1.geometry}
          material={materials.White}
        />
      </group>
      <group position={[-1.26, -0.082, -2.172]} scale={[0.157, 0.201, 0.041]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube040.geometry}
          material={materials.Brown3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube040_1.geometry}
          material={materials.White}
        />
      </group>
      <group position={[-1.278, 0.828, -2.172]} scale={[0.243, 0.179, 0.041]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041.geometry}
          material={materials.Brown4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041_1.geometry}
          material={materials.White}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={materials.Cream2}
        position={[0.828, -0.686, -1.692]}
        rotation={[-Math.PI / 2, 0, 0.381]}
        scale={[0.209, 0.286, 0.041]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials['Dark Yellow']}
        position={[-1.841, -0.38, 0.305]}
        scale={0.168}
      />
      <group
        position={[-0.936, -1.793, 1.871]}
        rotation={[-1.898, 0, -Math.PI]}
        scale={[-0.061, -0.558, -0.061]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials.Brown5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_2.geometry}
          material={materials.Green}
        />
      </group>
      <group
        position={[-1.111, -1.793, 1.871]}
        rotation={[-1.898, 0, -Math.PI]}
        scale={[-0.061, -0.558, -0.061]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_1.geometry}
          material={materials.Brown5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_2.geometry}
          material={materials.Blue}
        />
      </group>
      <group
        position={[-1.023, -1.674, 1.871]}
        rotation={[-1.898, 0, -Math.PI]}
        scale={[-0.061, -0.558, -0.061]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016_1.geometry}
          material={materials.Brown5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016_2.geometry}
          material={materials.Yellow}
        />
      </group>
      <group
        position={[-0.375, 1.891, -1.681]}
        rotation={[-2.21, 0, -Math.PI]}
        scale={[-0.061, -0.558, -0.061]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder017_1.geometry}
          material={materials.Brown5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder017_2.geometry}
          material={materials.Blue}
        />
      </group>
      <group
        position={[-0.165, 1.891, -1.681]}
        rotation={[-2.208, -0.058, -3.063]}
        scale={[-0.061, -0.558, -0.061]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018_1.geometry}
          material={materials.Brown5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018_2.geometry}
          material={materials.Orange}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={materials['Dark Yellow']}
        position={[-1.65, 1.326, -0.846]}
        scale={0.157}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002.geometry}
        material={materials['Dark Yellow']}
        position={[-2.002, 1.326, -0.827]}
        rotation={[0, -0.111, 0]}
        scale={0.157}
      />
      <group position={[-1.587, -0.676, 0.254]} scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_1.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_2.geometry}
          material={materials.Blue}
        />
      </group>
      <group
        position={[-1.602, 1.04, 0.751]}
        rotation={[-Math.PI, 0.934, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder030_1.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder030_2.geometry}
          material={materials.Blue}
        />
      </group>
      <group
        position={[-1.646, 1.04, 0.692]}
        rotation={[-Math.PI, 0.934, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder031_1.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder031_2.geometry}
          material={materials.Orange}
        />
      </group>
      <group
        position={[-1.71, 1.04, 0.773]}
        rotation={[-Math.PI, 0.934, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder032_1.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder032_2.geometry}
          material={materials['Dark green']}
        />
      </group>
      <group
        position={[-1.755, 1.04, 0.714]}
        rotation={[-Math.PI, 0.934, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder033_1.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder033_2.geometry}
          material={materials.Yellow}
        />
      </group>
      <group
        position={[-1.617, 1.04, 0.865]}
        rotation={[Math.PI, -0.241, Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder034_1.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder034_2.geometry}
          material={materials.Orange}
        />
      </group>
      <group
        position={[-1.689, 1.04, 0.883]}
        rotation={[Math.PI, -0.241, Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder035_1.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder035_2.geometry}
          material={materials.Orange}
        />
      </group>
      <group
        position={[-1.818, 1.04, 0.854]}
        rotation={[-Math.PI, 0.415, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder036_1.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder036_2.geometry}
          material={materials.Blue}
        />
      </group>
      <group
        position={[-1.886, 1.04, 0.824]}
        rotation={[-Math.PI, 0.415, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder037_1.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder037_2.geometry}
          material={materials.Orange}
        />
      </group>
      <group
        position={[-1.852, 1.04, 0.69]}
        rotation={[-Math.PI, 0.415, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder038.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder038_1.geometry}
          material={materials.Blue}
        />
      </group>
      <group
        position={[-1.92, 1.04, 0.66]}
        rotation={[-Math.PI, 0.415, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder039.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder039_1.geometry}
          material={materials.Orange}
        />
      </group>
      <group
        position={[-1.685, -0.655, -0.378]}
        rotation={[-Math.PI / 2, 0, -2.28]}
        scale={[-0.061, -0.558, -0.061]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder040.geometry}
          material={materials.Brown5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder040_1.geometry}
          material={materials.Orange}
        />
      </group>
      <group
        position={[1.005, -0.616, -1.61]}
        rotation={[0, 1.442, 0]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder041.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder041_1.geometry}
          material={materials.Blue}
        />
      </group>
      <group
        position={[0.921, -0.616, -1.743]}
        rotation={[0, 1.442, 0]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder042.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder042_1.geometry}
          material={materials.Yellow}
        />
      </group>
      <group
        position={[0.915, -0.616, -1.539]}
        rotation={[-Math.PI, 0.524, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder043.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder043_1.geometry}
          material={materials.Orange}
        />
      </group>
      <group
        position={[0.777, -0.616, -1.686]}
        rotation={[-Math.PI, 1.18, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder044.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder044_1.geometry}
          material={materials['Dark green']}
        />
      </group>
      <group
        position={[0.867, -0.616, -1.828]}
        rotation={[-Math.PI, 1.18, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder045.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder045_1.geometry}
          material={materials.Blue}
        />
      </group>
      <group
        position={[0.839, -0.616, -1.896]}
        rotation={[-Math.PI, 1.18, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder046.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder046_1.geometry}
          material={materials.Orange}
        />
      </group>
      <group
        position={[0.704, -0.616, -1.829]}
        rotation={[-Math.PI, 1.18, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder047.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder047_1.geometry}
          material={materials.Orange}
        />
      </group>
      <group
        position={[0.777, -0.616, -1.497]}
        rotation={[-Math.PI, 1.18, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder048.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder048_1.geometry}
          material={materials.Yellow}
        />
      </group>
      <group
        position={[0.809, -0.616, -1.591]}
        rotation={[-Math.PI, 1.18, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder049.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder049_1.geometry}
          material={materials.Black}
        />
      </group>
      <group
        position={[0.915, -0.616, -1.627]}
        rotation={[-Math.PI, 0.524, -Math.PI]}
        scale={[0.031, 0.048, 0.031]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder050.geometry}
          material={materials.Cream4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder050_1.geometry}
          material={materials.Orange}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={materials.Cream2}
        position={[-1.806, 0.984, 1.309]}
        rotation={[Math.PI, -0.021, Math.PI]}
        scale={[0.727, 1.057, 0.727]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials.Brown4}
        position={[-1.829, 1.186, -0.84]}
        rotation={[0, 0.04, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials.Cream2}
        position={[-1.829, 1.186, -0.231]}
        rotation={[0, -0.009, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials.Cream4}
        position={[-1.781, 1.103, 0.31]}
        rotation={[0, -0.167, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials.Brown}
        position={[-1.774, 1.032, 0.799]}
        rotation={[-0.005, -0.21, 0.001]}
        scale={[0.66, 0.324, 0.66]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials.Cream2}
        position={[-0.277, 1.814, -1.743]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.263, 1.285, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials.Cream2}
        position={[0.225, 1.758, -1.743]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials.Cream2}
        position={[-1.737, -1.862, -0.878]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials.Brown5}
        position={[1.885, -0.694, -1.67]}
        rotation={[0, -1.074, 0]}
        scale={[1.263, 0.698, 1.254]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={materials.Cream2}
        position={[-0.492, -0.69, -1.623]}
        rotation={[-Math.PI, 1.041, -Math.PI]}
        scale={[1.089, 0.88, 1.082]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_1.geometry}
        material={materials['Brown.2']}
      />
      <mesh castShadow receiveShadow geometry={nodes.Cube_2.geometry} material={materials.Cream} />
    </group>
  )
}

useGLTF.preload('/room.glb')
