import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Cube_1: THREE.Mesh
    Cube_2: THREE.Mesh
    Cube001: THREE.Mesh
    Masa: THREE.Mesh
    Cube004_1: THREE.Mesh
    Cube004_2: THREE.Mesh
    Dolap_sag2: THREE.Mesh
    Dolap_ustu: THREE.Mesh
    Raf_sag: THREE.Mesh
    Cube010_1: THREE.Mesh
    Cube010_2: THREE.Mesh
    Floor: THREE.Mesh
    Kupa: THREE.Mesh
    Saksı: THREE.Mesh
    Pencere: THREE.Mesh
    Cube012_1: THREE.Mesh
    Cube012_2: THREE.Mesh
    Circle_1: THREE.Mesh
    Circle_2: THREE.Mesh
    Circle001_1: THREE.Mesh
    Circle001_2: THREE.Mesh
    Cube021: THREE.Mesh
    Raf_sag001: THREE.Mesh
    Sapka002: THREE.Mesh
    Circle006: THREE.Mesh
    Circle006_1: THREE.Mesh
    Sapka004: THREE.Mesh
    Circle008: THREE.Mesh
    Circle008_1: THREE.Mesh
    Sapka006: THREE.Mesh
    Sapka007: THREE.Mesh
    Sapka008: THREE.Mesh
    Plane001: THREE.Mesh
    Plane002: THREE.Mesh
    Plane003: THREE.Mesh
    Plane004: THREE.Mesh
    Plane006: THREE.Mesh
    Plane007: THREE.Mesh
    Plane008: THREE.Mesh
    Plane009: THREE.Mesh
    Plane010: THREE.Mesh
    Plane011: THREE.Mesh
    Plane012: THREE.Mesh
    Plane013: THREE.Mesh
    Plane014: THREE.Mesh
    Plane015: THREE.Mesh
    Plane016: THREE.Mesh
    Plane017: THREE.Mesh
    Plane018: THREE.Mesh
    Plane019: THREE.Mesh
    Plane020: THREE.Mesh
    Plane021: THREE.Mesh
    Plane022: THREE.Mesh
    Plane042: THREE.Mesh
    Cube: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    Cube011: THREE.Mesh
    Cube012: THREE.Mesh
    Cube013: THREE.Mesh
    Cube014: THREE.Mesh
    Cube015: THREE.Mesh
    Cube016: THREE.Mesh
    Cube031: THREE.Mesh
    Cube032: THREE.Mesh
    Cube033: THREE.Mesh
    Cube034: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder005: THREE.Mesh
    Cylinder009: THREE.Mesh
    Plane: THREE.Mesh
    Plane005: THREE.Mesh
    Plane023: THREE.Mesh
    Plane024: THREE.Mesh
    Plane025: THREE.Mesh
    Circle: THREE.Mesh
    Plane026: THREE.Mesh
    Plane027: THREE.Mesh
    Plane028: THREE.Mesh
    Plane029: THREE.Mesh
    Plane030: THREE.Mesh
    Circle001: THREE.Mesh
    Plane031: THREE.Mesh
    Plane032: THREE.Mesh
    Plane033: THREE.Mesh
    Plane034: THREE.Mesh
    Plane035: THREE.Mesh
    Circle002: THREE.Mesh
    Plane036: THREE.Mesh
    Plane037: THREE.Mesh
    Plane038: THREE.Mesh
    Plane039: THREE.Mesh
    Plane040: THREE.Mesh
    BezierCurve: THREE.Mesh
    BezierCurve001: THREE.Mesh
    BezierCurve002: THREE.Mesh
    Cylinder010: THREE.Mesh
    Cylinder011: THREE.Mesh
    Plane041: THREE.Mesh
    Cube039: THREE.Mesh
    Cube039_1: THREE.Mesh
    Cube040: THREE.Mesh
    Cube040_1: THREE.Mesh
    Cube041: THREE.Mesh
    Cube041_1: THREE.Mesh
    Cube030: THREE.Mesh
    Sphere: THREE.Mesh
    Cylinder005_1: THREE.Mesh
    Cylinder005_2: THREE.Mesh
    Cylinder015_1: THREE.Mesh
    Cylinder015_2: THREE.Mesh
    Cylinder016_1: THREE.Mesh
    Cylinder016_2: THREE.Mesh
    Cylinder017_1: THREE.Mesh
    Cylinder017_2: THREE.Mesh
    Cylinder018_1: THREE.Mesh
    Cylinder018_2: THREE.Mesh
    Sphere001: THREE.Mesh
    Sphere002: THREE.Mesh
    Cylinder019_1: THREE.Mesh
    Cylinder019_2: THREE.Mesh
    Cylinder030_1: THREE.Mesh
    Cylinder030_2: THREE.Mesh
    Cylinder031_1: THREE.Mesh
    Cylinder031_2: THREE.Mesh
    Cylinder032_1: THREE.Mesh
    Cylinder032_2: THREE.Mesh
    Cylinder033_1: THREE.Mesh
    Cylinder033_2: THREE.Mesh
    Cylinder034_1: THREE.Mesh
    Cylinder034_2: THREE.Mesh
    Cylinder035_1: THREE.Mesh
    Cylinder035_2: THREE.Mesh
    Cylinder036_1: THREE.Mesh
    Cylinder036_2: THREE.Mesh
    Cylinder037_1: THREE.Mesh
    Cylinder037_2: THREE.Mesh
    Cylinder038: THREE.Mesh
    Cylinder038_1: THREE.Mesh
    Cylinder039: THREE.Mesh
    Cylinder039_1: THREE.Mesh
    Cylinder040: THREE.Mesh
    Cylinder040_1: THREE.Mesh
    Cylinder041: THREE.Mesh
    Cylinder041_1: THREE.Mesh
    Cylinder042: THREE.Mesh
    Cylinder042_1: THREE.Mesh
    Cylinder043: THREE.Mesh
    Cylinder043_1: THREE.Mesh
    Cylinder044: THREE.Mesh
    Cylinder044_1: THREE.Mesh
    Cylinder045: THREE.Mesh
    Cylinder045_1: THREE.Mesh
    Cylinder046: THREE.Mesh
    Cylinder046_1: THREE.Mesh
    Cylinder047: THREE.Mesh
    Cylinder047_1: THREE.Mesh
    Cylinder048: THREE.Mesh
    Cylinder048_1: THREE.Mesh
    Cylinder049: THREE.Mesh
    Cylinder049_1: THREE.Mesh
    Cylinder050: THREE.Mesh
    Cylinder050_1: THREE.Mesh
    Cube026: THREE.Mesh
    Cube022: THREE.Mesh
    Cube023: THREE.Mesh
    Cube024: THREE.Mesh
    Cube025: THREE.Mesh
    Cube017: THREE.Mesh
    Cube018: THREE.Mesh
    Cube019: THREE.Mesh
    Cube020: THREE.Mesh
    Cube035: THREE.Mesh
  }
  materials: {
    ['Brown.2']: THREE.MeshStandardMaterial
    Cream: THREE.MeshStandardMaterial
    Brown4: THREE.MeshStandardMaterial
    Brown5: THREE.MeshStandardMaterial
    Brown: THREE.MeshStandardMaterial
    Brown6: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Green: THREE.MeshStandardMaterial
    Cream3: THREE.MeshStandardMaterial
    Orange: THREE.MeshStandardMaterial
    Cream4: THREE.MeshStandardMaterial
    Blue: THREE.MeshStandardMaterial
    ['Dark green']: THREE.MeshPhysicalMaterial
    winddow_emission: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    ['Dark Yellow']: THREE.MeshStandardMaterial
    Yellow: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    Brown3: THREE.MeshStandardMaterial
    Cream2: THREE.MeshStandardMaterial
  }
}